/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hormiguero;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Ivanl
 */
public class Interfaz extends javax.swing.JFrame {
    private Refugio refugio;
    private Insecto insecto;
    private Contador contador;
    /**
     * Creates new form Interfaz
     */
    public Interfaz(Refugio refugio, Insecto insecto, Contador contador) {
        this.contador = contador;
        this.refugio = refugio;
        this.insecto = insecto;
        initComponents();
        // Configuración del JFrame
        setTitle("Mi JFrame en pantalla completa");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Obtener la resolución de pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        
        // Establecer el tamaño del JFrame al tamaño de pantalla
        //setSize(screenSize.width, screenSize.height);
        
        // Centrar el JFrame
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        generarInsecto = new javax.swing.JButton();
        pausaPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        generarInsecto.setText("Generar insecto");
        generarInsecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarInsectoActionPerformed(evt);
            }
        });

        pausaPlay.setText("Pausa");
        pausaPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(pausaPlay)
                .addGap(125, 125, 125)
                .addComponent(generarInsecto)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(513, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generarInsecto)
                    .addComponent(pausaPlay))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarInsectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarInsectoActionPerformed
        if (refugio.isAtaque()){
            System.out.println("Ya hay un insecto atacando el hormiguero");
        }
        else{
            if (contador.getNumSoldados() == 0){
                System.out.println("Se necesita al menos una hormiga soldado para poder defender el hormiguero");
            }
            else{
                if (!contador.getPlay()){
                    System.out.println("No se puede generar un insecto mientras el programa está pausado");
                }
                else{
                    refugio.setAtaque(true);
                    insecto.GenerarInsecto();
                }
            }
        }
    }//GEN-LAST:event_generarInsectoActionPerformed

    private void pausaPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaPlayActionPerformed
        if (contador.getPlay()){
            pausaPlay.setText("Play");
            contador.setPlay(false);
            for (Thread thread : contador.getListaHormigas()){
                if (thread != null){
                    thread.interrupt();
                }
            }
        }
        else{
            pausaPlay.setText("Pausa");
            contador.setPlay(true);
            synchronized(contador.getBloqueoPausa()){
                contador.getBloqueoPausa().notifyAll();
            }
        }
    }//GEN-LAST:event_pausaPlayActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generarInsecto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pausaPlay;
    // End of variables declaration//GEN-END:variables
}
